name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: self-hosted

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp /env/laravel-inertia.env .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run migration Migration
        run: php artisan migrate --force
      - name: Optimize
        run: php artisan optimize
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install pachages
        run: npm install
      - name: Build
        run: npm run build
